### ISSUE TITLE
AGEM sometimes blocks on Split CIFAR 100 

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/reproducible-continual-learning#16]
This requires further investigation

**Comment by AndreaCossu** [comment]
The problem does not happen with GEM, nor with AGEM on Permuted MNIST. 
On Split CIFAR-100, the first experiences are fine, but training becomes increasingly slower up until a point in which it is basically stuck. The problem seems to be somewhat related to dataloading of / backpropagation on the buffer sample at each iteration.

**Comment by AntonioCarta** [comment]
wild guess: there is a missing detach somewhere and it's backpropagating where it shouldn't?

**Comment by AndreaCossu** [comment]
may be, but it is strange that this happens only with CIFAR-100 then. It seems more of a dataloading issue (still strange). I plan to profile the steps and get some more insights.

**Comment by AndreaCossu** [comment]
The bug has been tracked and solved in the avalanche repo at [this issue](https://github.com/ContinualAI/avalanche/issues/950)
