### ISSUE TITLE
Reproduce Greedy Sample Selection (GSS) results - greedy version

### ISSUE THREAD

**Issue by AndreaCossu** [ContinualAI/reproducible-continual-learning#9]
[Link to the paper](https://proceedings.neurips.cc/paper/2019/file/e562cd9c0768d5464b64cf61da7fc6bb-Paper.pdf)

**Comment by AntonioCarta** [comment]
we need to take this from Avalanche: [https://github.com/ContinualAI/avalanche/blob/master/examples/gss_mnist.py](https://github.com/ContinualAI/avalanche/blob/master/examples/gss_mnist.py)
